name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Server
        run: |
          ssh user@server "cd /home/user/Fmie--primary && git pull && npm install --prefix keepalive && pm2 restart app"